### ISSUE TITLE
Unable to resolve Vault dependency

### ISSUE THREAD

**Issue by Magnum97** [spigradle/spigradle#44]
I have Vault as a dependency, it is listed in the spigot block of build.gradle and is included in the generated plugin.yml. 
However, when running prepareSpigotPlugins I get a message that it cannot resolve plugin dependencies. I was using 2.1.1 of Spigradle but just updated to 2.2.3 but no changes during prepare task.

Kindly let me know if I can provide any further helpful information. Thank you for this amazing tool.

![image](https://user-images.githubusercontent.com/39318657/111899420-d6db1780-89e9-11eb-9fb5-c8951e61a087.png)

**Comment by EntryPointKR** [comment]
Hi @Magnum97 , I'm sorry for the late response!
Put `jitpack()` in repositories, `vaultAll()` in dependencies instead of `vault()` should be work.

```kotlin
repositories {
    jitpack() // for Vault
}

dependencies {
    // ...
    compileOnly(vaultAll()) {  // for Vault instead of Vault-API
        isTransitive = false // for avoid bStats that Vault transitively requires
    }
}
```

`vault()` = Vault-API
`vaultAll()` = Vault (executable full .jar)
I know this can be confusing while the `spigot()` is `spigot-api`. In Spigradle 3.0, I'll re-consider this design.
Thanks!

**Comment by Magnum97** [comment]
Thank you! No worries, we are all quite busy I'm sure. I am happy to hear that this is still an active project.
